### ISSUE TITLE
allow to configure repositories for syncLibs

### ISSUE THREAD

**Issue by nkiesel** [jmfayard/gradle-kotlin-dsl-libs#20]
We use a setup where our build can only uses artifacts from our in-house artifactory repository (basically a means to control what our developers are allowed to use).  However, for "syncLibs" to work it needs access to external repos.  Right now I slove that by manually adding "jcenter()" to "build.gradle" before running "syncLibs" (and then reverting that change again).

What would be really cool would be if I instead could configure "syncLibs" to use "jcenter" (or "mavenCentral" or other repos) in addition to the normal repositories.

**Comment by nkiesel** [comment]
Another issue seems to be that the place where I add "jcenter()" matters a lot: seems that if I put that below my local artifactory reference, it does not find newer versions that are available on "jcenter".  I think that is a "this is how gradle is designed" problem, but might surprise your users (and/or lead to invalid/incomplete results).  Thus, if syncLibs would allow to explicitly specify "additional repos", it could either always put these as the first ones to use, or perhaps support a "first"/"last" configuration for the user to decide.

**Comment by nkiesel** [comment]
I now realize that this is a request for the "dependencyUpdates" plugin and not for this one.  I opened issue https://github.com/ben-manes/gradle-versions-plugin/issues/274 for this and will close this issue.

**Comment by jmfayard** [comment]
@nkiesel Correct, this would be a configuration option for the gradle versions plugin. Let me know if you it works for you, I could add a paragraph about this in the README.

**Comment by nkiesel** [comment]
Yes, worked for me.  Looks at the issue linked above for my current solution.  One caveat is that my project has a multi-project setup, not sure if the same version works for single-project setups or if the `allprojects` has to be removed for that.

Another word of advice (which also applies more to the underlying versions plugin) is that at least with gradle 4.9.x the order of repos is critical.  As a concrete example, I have a dependency where jcenter has 2.4 as the latest version and mavencentral has 2.3, and depending on which comes first the plugin (and thus your plugin) will report differnt values for the latest version.  For most dependencies that might not matter as long as you have either jcenter or mavencentral as the top repo because the are 99% or so in sync anyway.  But mentioning that in your README might be helpful for some users.
