### ISSUE TITLE
SyncLibs generate wrong output file 

### ISSUE THREAD

**Issue by giacomoParisi** [jmfayard/gradle-kotlin-dsl-libs#4]
I added these 2 dependencies to the build.gradle file:

"com.android.tools.build:gradle:3.2.1"
 "Io.fabric.tools:gradle:1.26.1"

But the object Libs (for these 2 dependencies) is not generated correctly, because I get a mix of 2.
I get only this:
const val com_android_tools_build_gradle: String ="io.fabric.tools:gradle:" + Versions.com_android_tools_build_gradle

which is the fabric library but with the name of the other, while "com.android.tools.build:gradle" is not present

**Comment by jmfayard** [comment]
Thanks for the report, I will fix this!

**Comment by jmfayard** [comment]
@giacomoParisi 
It should be fixed with

```
plugins {
  id("jmfayard.github.io.gradle-kotlin-dsl-libs") version "0.2.4"
}
```
